### ISSUE TITLE
Failure to set the application classpath in Info.plist

### ISSUE THREAD

**Issue by sortega** [kavedaa/sbt-javafx#22]
Hello, I'm trying to package an application on Mac OS X 10.10.3 (Mavericks) but the resulting application cannot be run. When launched from the terminal this is the output:
```console
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: scalafx/application/JFXApp$Parameters
at java.lang.Class.getDeclaredMethods0(Native Method)
at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
at java.lang.Class.getMethod0(Class.java:3018)
at java.lang.Class.getMethod(Class.java:1784)
at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: scalafx.application.JFXApp$Parameters
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 7 more
2015-05-27 15:37:24.690 Coinffeine[9202:10336963] .:Failed to launch JVM
```

The relevant section on the Info.plist is empty:
```xml
<key>JVMAppClasspath</key>
<string></string> 
```

And we configure the plugin as follows ([full config](https://github.com/Coinffeine/coinffeine/blob/master/coinffeine-gui/build.sbt)):
```scala
jfxSettings

JFX.vendor := "Coinffeine S.L."

JFX.copyright := "Copyright (c) 2013-2015 Coinffeine S.L."

JFX.license := "Coinffeine License"

JFX.artifactBaseNameValue := "packages"

JFX.mainClass := Some("coinffeine.gui.Main")

JFX.title := "Coinffeine"

JFX.nativeBundles := "all"

JFX.pkgResourcesDir := Seq(
  baseDirectory.value / "src" / "deploy",
  crossTarget.value / "deploy"
).mkString(":")

JFX.verbose := true
```

**Comment by shemnon** [comment]
There are two quasi-related issues.  First, there is a bug in Java 8u40, 8u45 (and likely 8u51) that isn't sending the auto-detected classpath to the mac app launcher.  This is proven fixed in 8u60.

But, there are hooks to let the user hard-code the classpath in 8u40 (and 8u20).  This may be desirable for OSGi and other such framework where only some of the provided jars should start on the classpath.
Since you are passing throught a literal ant script I'll describe the ant method.

Under fx:deploy you can add fx:bundleArgument of value 'classpath', like so...

    <fx:deploy .... >
      <fx:bundleArgument arg="classpath" value="foo.jar lib/bar.jar"/>
    </fx:deploy>

so there needs to be a sbt config section to either explicitly set this classapth value, or a more generic method.  

The more generic method would be a string to string map and would create one bundleArgument for each entry.  While there are known values for this map, the design is that it can be set to arbitrary keys and values to adapt to the needs of arbitrary bundlers.

**Comment by shemnon** [comment]
Looked at a code, it's a bug in the plugin.

jarFile at line 177 is generated in distDir.  DistDir is also where you tell fxDeploy to generate the output.  This is bad, the file gets clobbered by JNLP generation and undoes key jar file changes.  Point jarFile literally anywhere else but distDir and you will be fine.

**Comment by sortega** [comment]
Is there any workaround other than forking the plugin?

**Comment by kavedaa** [comment]
Thanks Danno, I'll take a look and fix this as soon as I can.

**Comment by kavedaa** [comment]
Sebastian, could you try 0.7.1-SNAPSHOT and see if it solves your problem? (Have to clone and build it locally.)

**Comment by apoloval** [comment]
Tested with `0.7.1-SNAPSHOT`, but it doesn't work. fe66be7a42547705315635fd036469b4f87edaf7 doesn't fix the issue.
